-- MySQL Script generated by MySQL Workbench
-- Tue 02 Aug 2016 08:18:34 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eabdbw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eabdbw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eabdbw` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `eabdbw` ;

-- -----------------------------------------------------
-- Table `eabdbw`.`DrugNames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`DrugNames` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`DrugNames` (
  `DrugNameId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `GenericName` VARCHAR(100) NOT NULL,
  `BrandName` VARCHAR(100) NULL,
  PRIMARY KEY (`DrugNameId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`Formulations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`Formulations` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`Formulations` (
  `FormulationId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Formulation` VARCHAR(50) NULL,
  PRIMARY KEY (`FormulationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`Units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`Units` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`Units` (
  `UnitId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Unit` VARCHAR(45) NULL,
  PRIMARY KEY (`UnitId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`DrugDoses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`DrugDoses` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`DrugDoses` (
  `DrugDoseId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Dose` INT NULL,
  `DoseUnitId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`DrugDoseId`, `DoseUnitId`),
  INDEX `fk_MedicationDoses_DoseUnits1_idx` (`DoseUnitId` ASC),
  CONSTRAINT `fk_MedicationDoses_DoseUnits1`
    FOREIGN KEY (`DoseUnitId`)
    REFERENCES `eabdbw`.`Units` (`UnitId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`Drugs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`Drugs` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`Drugs` (
  `DrugId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FormulationId` BIGINT UNSIGNED NOT NULL,
  `DrugNameId` BIGINT UNSIGNED NOT NULL,
  `DrugDoseId` BIGINT UNSIGNED NOT NULL,
  `DoseUnitId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`DrugId`, `FormulationId`, `DrugNameId`, `DrugDoseId`, `DoseUnitId`),
  INDEX `fk_MedicationFormulations_Formulations1_idx` (`FormulationId` ASC),
  INDEX `fk_Drugs_DrugNames1_idx` (`DrugNameId` ASC),
  INDEX `fk_Drugs_DrugDoses1_idx` (`DrugDoseId` ASC, `DoseUnitId` ASC),
  CONSTRAINT `fk_MedicationFormulations_Formulations1`
    FOREIGN KEY (`FormulationId`)
    REFERENCES `eabdbw`.`Formulations` (`FormulationId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Drugs_DrugNames1`
    FOREIGN KEY (`DrugNameId`)
    REFERENCES `eabdbw`.`DrugNames` (`DrugNameId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Drugs_DrugDoses1`
    FOREIGN KEY (`DrugDoseId` , `DoseUnitId`)
    REFERENCES `eabdbw`.`DrugDoses` (`DrugDoseId` , `DoseUnitId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`Stock` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`Stock` (
  `StockId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Amount` INT NOT NULL DEFAULT 0,
  `ExpirationDate` DATE NOT NULL,
  `Cost` DECIMAL NOT NULL,
  `IdealAmount` INT NULL,
  `DrugId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`StockId`, `DrugId`),
  INDEX `fk_Stock_Drugs1_idx` (`DrugId` ASC),
  CONSTRAINT `fk_Stock_Drugs1`
    FOREIGN KEY (`DrugId`)
    REFERENCES `eabdbw`.`Drugs` (`DrugId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`Specialties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`Specialties` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`Specialties` (
  `SpecialtyId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Specialty` VARCHAR(50) NULL,
  PRIMARY KEY (`SpecialtyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`Physicians`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`Physicians` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`Physicians` (
  `PhysicianId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(50) NULL,
  `MiddleName` VARCHAR(50) NULL,
  `LastName` VARCHAR(50) NULL,
  `Suffix` VARCHAR(50) NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `SpecialtyId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`PhysicianId`),
  INDEX `fk_Physicians_Specialties1_idx` (`SpecialtyId` ASC),
  CONSTRAINT `fk_Physicians_Specialties1`
    FOREIGN KEY (`SpecialtyId`)
    REFERENCES `eabdbw`.`Specialties` (`SpecialtyId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`Clinics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`Clinics` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`Clinics` (
  `ClinicId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `URL` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`ClinicId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`Prescriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`Prescriptions` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`Prescriptions` (
  `PrescriptionId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DispensesAllowed` VARCHAR(45) NULL,
  `DrugId` BIGINT UNSIGNED NOT NULL,
  `PhysicianId` BIGINT UNSIGNED NOT NULL,
  `ClinicId` BIGINT UNSIGNED NOT NULL,
  `Date` DATETIME NULL,
  PRIMARY KEY (`PrescriptionId`, `DrugId`, `PhysicianId`, `ClinicId`),
  INDEX `fk_Prescriptions_Drugs1_idx` (`DrugId` ASC),
  INDEX `fk_Prescriptions_Physicians2_idx` (`PhysicianId` ASC),
  INDEX `fk_Prescriptions_Clinics1_idx` (`ClinicId` ASC),
  CONSTRAINT `fk_Prescriptions_Drugs1`
    FOREIGN KEY (`DrugId`)
    REFERENCES `eabdbw`.`Drugs` (`DrugId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Prescriptions_Physicians2`
    FOREIGN KEY (`PhysicianId`)
    REFERENCES `eabdbw`.`Physicians` (`PhysicianId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Prescriptions_Clinics1`
    FOREIGN KEY (`ClinicId`)
    REFERENCES `eabdbw`.`Clinics` (`ClinicId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`MedicationDispensed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`MedicationDispensed` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`MedicationDispensed` (
  `MedicationDispensedId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NULL,
  `PrescriptionId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`MedicationDispensedId`, `PrescriptionId`),
  INDEX `fk_MedicationDispensed_Prescriptions1_idx` (`PrescriptionId` ASC),
  CONSTRAINT `fk_MedicationDispensed_Prescriptions1`
    FOREIGN KEY (`PrescriptionId`)
    REFERENCES `eabdbw`.`Prescriptions` (`PrescriptionId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`LabTests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`LabTests` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`LabTests` (
  `LabTestId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `LabTest` VARCHAR(45) NULL,
  `Cost` DECIMAL NULL COMMENT 'in dollars',
  PRIMARY KEY (`LabTestId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`LabTestsComponents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`LabTestsComponents` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`LabTestsComponents` (
  `LabTestComponentId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `LabTestComponent` VARCHAR(45) NULL,
  `LabTestComponentDefaultUnitId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`LabTestComponentId`),
  INDEX `fk_LabTestsComponents_Units1_idx` (`LabTestComponentDefaultUnitId` ASC),
  CONSTRAINT `fk_LabTestsComponents_Units1`
    FOREIGN KEY (`LabTestComponentDefaultUnitId`)
    REFERENCES `eabdbw`.`Units` (`UnitId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`LabComponentsAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`LabComponentsAssociation` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`LabComponentsAssociation` (
  `LabComponentAssociationId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `LabTestId` BIGINT UNSIGNED NOT NULL,
  `LabTestComponentId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`LabComponentAssociationId`, `LabTestId`, `LabTestComponentId`),
  INDEX `fk_LabComponentsAssociation_LabTests1_idx` (`LabTestId` ASC),
  INDEX `fk_LabComponentsAssociation_LabTestsComponents1_idx` (`LabTestComponentId` ASC),
  CONSTRAINT `fk_LabComponentsAssociation_LabTests1`
    FOREIGN KEY (`LabTestId`)
    REFERENCES `eabdbw`.`LabTests` (`LabTestId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LabComponentsAssociation_LabTestsComponents1`
    FOREIGN KEY (`LabTestComponentId`)
    REFERENCES `eabdbw`.`LabTestsComponents` (`LabTestComponentId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eabdbw`.`PatientLabTests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eabdbw`.`PatientLabTests` ;

CREATE TABLE IF NOT EXISTS `eabdbw`.`PatientLabTests` (
  `PatientLabTestId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `LabComponentAssociationId` BIGINT UNSIGNED NOT NULL,
  `PhysicianId` BIGINT UNSIGNED NOT NULL,
  `DateOrdered` VARCHAR(45) NULL,
  `DateResults` VARCHAR(45) NULL,
  `Value` VARCHAR(45) NULL,
  `ValueUnits` VARCHAR(45) NULL,
  `UnitId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`PatientLabTestId`, `LabComponentAssociationId`, `PhysicianId`),
  INDEX `fk_PatientLabTests_LabComponentsAssociation1_idx` (`LabComponentAssociationId` ASC),
  INDEX `fk_PatientLabTests_Physicians1_idx` (`PhysicianId` ASC),
  INDEX `fk_PatientLabTests_Units1_idx` (`UnitId` ASC),
  CONSTRAINT `fk_PatientLabTests_LabComponentsAssociation1`
    FOREIGN KEY (`LabComponentAssociationId`)
    REFERENCES `eabdbw`.`LabComponentsAssociation` (`LabComponentAssociationId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PatientLabTests_Physicians1`
    FOREIGN KEY (`PhysicianId`)
    REFERENCES `eabdbw`.`Physicians` (`PhysicianId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PatientLabTests_Units1`
    FOREIGN KEY (`UnitId`)
    REFERENCES `eabdbw`.`Units` (`UnitId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Data for table `eabdbw`.`Formulations`
-- -----------------------------------------------------
START TRANSACTION;
USE `eabdbw`;
INSERT INTO `eabdbw`.`Formulations` (`FormulationId`, `Formulation`) VALUES (DEFAULT, 'Oral');
INSERT INTO `eabdbw`.`Formulations` (`FormulationId`, `Formulation`) VALUES (DEFAULT, 'Intravenous');
INSERT INTO `eabdbw`.`Formulations` (`FormulationId`, `Formulation`) VALUES (DEFAULT, 'Sublingual');
INSERT INTO `eabdbw`.`Formulations` (`FormulationId`, `Formulation`) VALUES (DEFAULT, 'Intramuscular');
INSERT INTO `eabdbw`.`Formulations` (`FormulationId`, `Formulation`) VALUES (DEFAULT, 'Topical');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eabdbw`.`Units`
-- -----------------------------------------------------
START TRANSACTION;
USE `eabdbw`;
INSERT INTO `eabdbw`.`Units` (`UnitId`, `Unit`) VALUES (DEFAULT, 'mg');
INSERT INTO `eabdbw`.`Units` (`UnitId`, `Unit`) VALUES (DEFAULT, 'mL');
INSERT INTO `eabdbw`.`Units` (`UnitId`, `Unit`) VALUES (DEFAULT, 'g');
INSERT INTO `eabdbw`.`Units` (`UnitId`, `Unit`) VALUES (DEFAULT, '%');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eabdbw`.`LabTests`
-- -----------------------------------------------------
START TRANSACTION;
USE `eabdbw`;
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Basic Metabolic Panel (8)', 27.91);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'CBC With Differential/Platelet', 13.10);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'CBC No Differential/Platelet', 8.83);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'CBC Platelet; No Differential', 8.83);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Blood Count Manual Diff WBC', 7.12);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Platelet Count', 9.68);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Comp. Metabolic Panel (14)', 37.59);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Hb A1C', 15.66);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'HBsAg', 16.80);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'HCV Antibody', 19.93);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'HCV RNA Quant RT PCR', 54.96);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'HEP C Genotype', 183.09);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'HEP C Genotype Sibling CDM', 44.99);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'HEP C Genotype Sibling CDM', 138.10);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Hep A Ab IgM', 14.24);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Hepatic Function Panel (7)', 19.36);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Hepatitis B Surf Antigen', 16.80);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Hep B Core Ab IgM', 19.65);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Hepatitis Acute Panel', 68.37);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Hepatitis C Antibody', 19.93);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'HIV 1/2 Antibody', 23.29);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Lipid Profile (LP)', 15.38);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Cholesterol Total (inc in LP)', 9.11);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'HDL Cholesterol (inc in LP)', 15.38);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Triglycerides (inc in LP)', 8.54);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Lipase serum', NULL);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Free T4', 12.10);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'TSH', 21.18);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'LDL Cholesterol (inc in LP)', 12.81);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Monospot Screen Monospot', 25.91);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Smear Wet Mount', 12.53);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Occult Blood Feces', 5.41);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Glucose Blood', 6.55);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Glucose Qnt (1Hr Post Glucola)', 7.40);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Glucose CSF', 7.40);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Glucose Fluid', 7.40);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Glucose Urine', 7.40);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Hematocrit', 6.55);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Sed Rate RBC Non Auto', 8.54);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Urine Pregnancy Visual', 11.67);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Urinalysis Auto w/o Micro', 9.97);
INSERT INTO `eabdbw`.`LabTests` (`LabTestId`, `LabTest`, `Cost`) VALUES (DEFAULT, 'Urinalysis With Micro', 10.82);

COMMIT;
